Modification to 1.1.1
einpraegsam/femanagerextended pull request #5
Opened 2018-02-06 18:15 UTC by Footrotflat

Fixed - parameter createAction - PHP7 compatibility

2018-03-21 12:56 UTC, Keinbockwurst requested changes

2018-03-21 12:56 UTC, Keinbockwurst commented on Classes/Controller/EditController.php
> +    public function initializeCreateAction() {
I think this is wrong.. shouldnt it be initializeUpdateAction() ?

2018-03-21 13:57 UTC, Keinbockwurst commented on Classes/Controller/EditController.php
> +    public function initializeCreateAction() {
I tested this and yup, its wrong.

2018-08-07 16:14 UTC, Footrotflat commented
Yes you are right

2018-08-27 09:11 UTC, werkraum-admin commented
You can avoid the xClass by setting the ObjectType via the PropertyMapper

`/** @var \TYPO3\CMS\Extbase\Mvc\Controller\Argument $user */
            $user = $this->arguments['user'];
            $user->getPropertyMappingConfiguration()->setTargetTypeForSubProperty('user',
                \In2code\Femanagerextended\Domain\Model\User::class);`

2023-03-01 12:32 UTC, closed without merging